### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by EvansXu** [williamyang1991/Rerender_A_Video#107]
**The error message I receive is as follows:**

evans@evans:~/Work/Rerender_A_Video$ python3 rerender.py --cfg config/real2sculpture.json
logging improved.
Traceback (most recent call last):
  File "rerender.py", line 25, in <module>
    from flow.flow_utils import get_warped_and_mask
  File "/home/evans/Work/Rerender_A_Video/flow/flow_utils.py", line 258, in <module>
    flow_calc = FlowCalc()
  File "/home/evans/Work/Rerender_A_Video/flow/flow_utils.py", line 156, in __init__
    checkpoint = torch.load(model_path,
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

evans@evans:~/Work/Rerender_A_Video$ nvidia-smi 
Sun Nov  5 22:02:46 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA TITAN Xp                Off | 00000000:65:00.0  On |                  N/A |
| 23%   34C    P5              23W / 250W |    727MiB / 12288MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       865      G   /usr/lib/xorg/Xorg                          102MiB |
|    0   N/A  N/A      1469      G   /usr/lib/xorg/Xorg                          312MiB |
|    0   N/A  N/A      1596      G   /usr/bin/gnome-shell                         92MiB |
|    0   N/A  N/A      3353      G   /usr/lib/firefox/firefox                    204MiB |
+---------------------------------------------------------------------------------------+

**Comment by williamyang1991** [comment]
The Python "Pickle EOFError: Ran out of input" occurs when the file you are trying to open and load is empty. 
To solve this error, you need to make sure all the pretrained models are downloaded completely. 

Your error indictate the following model is not correctly downloaded.
https://github.com/williamyang1991/Rerender_A_Video/blob/a348e0a549f3856e58fe610b52eecb4972d1c992/install.py#L50-L53

**Comment by EvansXu** [comment]
@williamyang1991 Thanks for your enthusiastic reply!
After using python install.py, the result shows success without any error prompts. I can see the following information under the ./model. Is it correct?
evans@evans-MS-7A94:~/Work/Rerender_A_Video/models$ ls -l
total 0
-rw-rw-r-- 1 evans evans 0 11月  5 20:09 control_sd15_canny.pth
-rw-rw-r-- 1 evans evans 0 11月  5 20:09 control_sd15_hed.pth
-rw-rw-r-- 1 evans evans 0 11月  5 20:09 gmflow_sintel-0c07dcb3.pth
-rw-rw-r-- 1 evans evans 0 11月  5 20:09 vae-ft-mse-840000-ema-pruned.ckpt

by the way,  In file real2sculpture.json, it was found that file models/realisticVisionV20_v20.safetensors is needed ,but I can't find the file realisticVisionV20_v20.safetensors, May I ask if the error was caused by a missing rrealisticVisionV20_v20.safetensors. Thansk  a lot!

**Comment by williamyang1991** [comment]
Yes, you can download realisticVisionV20_v20.safetensors [here](https://huggingface.co/ckpt/realistic-vision-v20/blob/main/realisticVisionV20_v20.safetensors)

**Comment by EvansXu** [comment]
@williamyang1991 Thanks, I'll download it and have a try!
