### ISSUE TITLE
Some errors occurred during the "postprocess" procedure. How can i fix it?

### ISSUE THREAD

**Issue by MarcYugo** [williamyang1991/Rerender_A_Video#136]
When using this command "python video_blend.py result/man --beg 1 --end 352 --itv 10 --key keys  --output result/man/man.mp4 --fps 25.0 --n_proc 2  -ps" to combine images into a video, an error occurred.

The information provided for errors is as follows:

/usr/local/miniconda3/envs/rerender/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/miniconda3/envs/rerender/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/rerender/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda3/envs/rerender/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/rerender/video_blend.py", line 109, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/root/rerender/video_blend.py", line 96, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/root/rerender/blender/guide.py", line 97, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/root/rerender/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/rerender/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda3/envs/rerender/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/rerender/video_blend.py", line 109, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/root/rerender/video_blend.py", line 96, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/root/rerender/blender/guide.py", line 97, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/root/rerender/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
ebsynth: 7.8225085735321045
Traceback (most recent call last):
  File "video_blend.py", line 318, in <module>
    main(args)
  File "video_blend.py", line 267, in main
    process_seq(video_sequence, i, blend_histogram, blend_gradient)
  File "video_blend.py", line 198, in process_seq
    dist1s.append(load_error(bin_a, img_shape))
  File "video_blend.py", line 159, in load_error
    with open(bin_path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'result/man/out_1/0002.bin

**Comment by williamyang1991** [comment]
Please carefully read the [README.md - Installation or Running Fails?](https://github.com/williamyang1991/Rerender_A_Video/tree/main#issues). All details have been provided:

1. In case building ebsynth fails, we provides our complied [ebsynth](https://drive.google.com/drive/folders/1oSB3imKwZGz69q2unBUfcgmQpzwccoyD?usp=sharing)
2. `FileNotFoundError: [Errno 2] No such file or directory: 'xxxx.bin' or 'xxxx.jpg'`:
    - make sure your path only contains English letters or _ (https://github.com/williamyang1991/Rerender_A_Video/issues/18#issuecomment-1723361433)
    - find the code `python video_blend.py ...` in the error log and use it to manually run the ebsynth part, which is more stable than WebUI.
    - if some non-keyframes are generated but somes are not, rather than missing all non-keyframes in '/out_xx/', you may refer to https://github.com/williamyang1991/Rerender_A_Video/issues/38#issuecomment-1730668991
    - Enable the Execute permission of deps/ebsynth/bin/ebsynth
    - Enable the debug log to find more information https://github.com/williamyang1991/Rerender_A_Video/blob/d32b1d6b6c1305ddd06e66868c5dcf4fb7aa048c/video_blend.py#L22

**Comment by MarcYugo** [comment]
> Please carefully read the [README.md - Installation or Running Fails?](https://github.com/williamyang1991/Rerender_A_Video/tree/main#issues). All details have been provided:
> 
> 1. In case building ebsynth fails, we provides our complied [ebsynth](https://drive.google.com/drive/folders/1oSB3imKwZGz69q2unBUfcgmQpzwccoyD?usp=sharing)
> 2. `FileNotFoundError: [Errno 2] No such file or directory: 'xxxx.bin' or 'xxxx.jpg'`:
>    
>    * make sure your path only contains English letters or _ ([2 Major issues for Windows - Too many errors spent hours already to fix all - Pip freeze attached  #18 (comment)](https://github.com/williamyang1991/Rerender_A_Video/issues/18#issuecomment-1723361433))
>    * find the code `python video_blend.py ...` in the error log and use it to manually run the ebsynth part, which is more stable than WebUI.
>    * if some non-keyframes are generated but somes are not, rather than missing all non-keyframes in '/out_xx/', you may refer to [FileNotFoundError: [Errno 2] No such file or directory: 'videos/pexels-antoni-shkraba-8048492-540x960-25fps/out_1/0002.bin' #38 (comment)](https://github.com/williamyang1991/Rerender_A_Video/issues/38#issuecomment-1730668991)
>    * Enable the Execute permission of deps/ebsynth/bin/ebsynth
>    * Enable the debug log to find more information https://github.com/williamyang1991/Rerender_A_Video/blob/d32b1d6b6c1305ddd06e66868c5dcf4fb7aa048c/video_blend.py#L22

Thank you. The problem has been solved.
