### ISSUE TITLE
Getting keyerror "dataset" when running the gradio ui

### ISSUE THREAD

**Issue by sausax** [williamyang1991/Rerender_A_Video#14]
`Traceback (most recent call last):
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/gradio/routes.py", line 282, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "/mnt/1c418dd9-a3c3-4278-870a-fe3a7069416b/github/Rerender_A_Video/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 504, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'`

**Comment by FurkanGozukara** [comment]
same error

trying to solve right now

**Comment by FurkanGozukara** [comment]
yep not useable atm until this bug is fixed

here some same bug other issues

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11855

https://github.com/gradio-app/gradio/issues/4083

a dirty fix which doesn't work : https://github.com/jexom/sd-webui-depth-lib/issues/36

@williamyang1991 
@SingleZombie

**Comment by SingleZombie** [comment]
I think the error is caused by a incompatible Gradio version. Could you provide us with your Gradio version? Our default gradio version is 3.33.1.

**Comment by cmeka** [comment]
> I think the error is caused by a incompatible Gradio version. Could you provide us with your Gradio version? Our default gradio version is 3.33.1.

The [requirements.txt](https://github.com/williamyang1991/Rerender_A_Video/blob/main/requirements.txt) and https://github.com/williamyang1991/Rerender_A_Video/blob/main/environment.yml both specify gradio==3.33.1.
I was able to solve this by installing the latest version with: `pip install gradio==3.44.3`

**Comment by Meatfucker** [comment]
Upgrading to 3.44.3 got the dataset error to go away, but its now throwing this error.
`(rerender) PS D:\ML\apps\Rerender_A_Video> python .\webUI.py
logging improved.
Traceback (most recent call last):
  File ".\webUI.py", line 839, in <module>
    args = cfg_to_input(config_path)
  File ".\webUI.py", line 199, in cfg_to_input
    cfg.create_from_path(filename)
  File "D:\ML\apps\Rerender_A_Video\src\config.py", line 102, in create_from_path
    kwargs['input_path'] = cfg['input']
KeyError: 'input'`

**Comment by michaelgold** [comment]
> > I think the error is caused by a incompatible Gradio version. Could you provide us with your Gradio version? Our default gradio version is 3.33.1.
> 
> The [requirements.txt](https://github.com/williamyang1991/Rerender_A_Video/blob/main/requirements.txt) and [environment.yml](https://github.com/williamyang1991/Rerender_A_Video/blob/main/environment.yml) both specify gradio==3.33.1 I was able to solve this by installing the latest version with: `pip install gradio==3.44.3`

This worked for me on Windows
