### ISSUE TITLE
Can't go past Installation step 4

### ISSUE THREAD

**Issue by pellaaa93** [williamyang1991/Rerender_A_Video#19]
after completing first 3 installation steps I get this error if I try to run demo or launch ui (python rerender.py --cfg config/real2sculpture.json / python webUI.py):

PS E:\Programmi\Rerender_A_Video-main> python webUI.py
logging improved.
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpy.py", line 93, in run
    self.process = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Programmi\Rerender_A_Video-main\webUI.py", line 856, in <module>
    gr.Examples(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\helpers.py", line 54, in create_examples
    examples_obj = Examples(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\helpers.py", line 201, in __init__
    self.processed_examples = [
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\helpers.py", line 202, in <listcomp>
    [
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\helpers.py", line 203, in <listcomp>
    component.postprocess(sample)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\components.py", line 2190, in postprocess
    processed_files = (self._format_video(y), None)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\components.py", line 2237, in _format_video
    and not processing_utils.video_is_playable(video)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\processing_utils.py", line 498, in video_is_playable
    output = probe.run(stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ffmpy.py", line 98, in run
    raise FFExecutableNotFoundError(
ffmpy.FFExecutableNotFoundError: Executable 'ffprobe' not found

**Comment by SingleZombie** [comment]
I think the bug is caused by `ffmpy` library and not by our codes. Please search the solution for error `ffmpy.FFExecutableNotFoundError: Executable 'ffprobe' not found`.

**Comment by pellaaa93** [comment]
hey thanks for answeringI managed to fix it... but now I am stuck here:

PS E:\Programmi\Rerender_A_Video-main> python webUI.py
logging improved.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

and of course that link doesn't open anything..
I installed rerender, controlnet, ebsynth, gmflow directly with .zip from github

**Comment by williamyang1991** [comment]
Maybe using 127.0.0.1:7860 ?
If that is still not working, you can turn on the public link, by setting `block.launch(share=True)`

https://github.com/williamyang1991/Rerender_A_Video/blob/bc2d1f2b4b417dcf8c5d5501fa0c8745218d1372/webUI.py#L927

**Comment by pellaaa93** [comment]
yeah I tried this before reading your comment and it worked, lets see if I can render now!

**Comment by pellaaa93** [comment]
I can access UI now but as I open the page I got this error:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\routes.py", line 282, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 504, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'

**Comment by williamyang1991** [comment]
You can upgrade  the latest version of gradio with: `pip install gradio==3.44.3`

https://github.com/williamyang1991/Rerender_A_Video/issues/14#issuecomment-1722778672

**Comment by pellaaa93** [comment]
fixed thanks! but now unfortunately as I try to render 1st frame using provided marble statue example I got this error (only thing I changed is to add DreamShaper 8 model in sd_model_cfg.py):

No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./deps/ControlNet/models/cldm_v15.yaml]
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Programmi\Rerender_A_Video-main\webUI.py", line 258, in process1
    global_state.update_sd_model(cfg.sd_model, cfg.control_type)
  File "E:\Programmi\Rerender_A_Video-main\webUI.py", line 90, in update_sd_model
    load_state_dict('./models/control_sd15_canny.pth',
  File "E:\Programmi\Rerender_A_Video-main\deps\ControlNet\cldm\model.py", line 18, in load_state_dict
    state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by pellaaa93** [comment]
fixed thanks! but now unfortunately as I try to render 1st frame using provided marble statue example I got this error (only thing I changed is to add DreamShaper 8 model in sd_model_cfg.py):

No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./deps/ControlNet/models/cldm_v15.yaml]
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\Programmi\Rerender_A_Video-main\webUI.py", line 258, in process1
    global_state.update_sd_model(cfg.sd_model, cfg.control_type)
  File "E:\Programmi\Rerender_A_Video-main\webUI.py", line 90, in update_sd_model
    load_state_dict('./models/control_sd15_canny.pth',
  File "E:\Programmi\Rerender_A_Video-main\deps\ControlNet\cldm\model.py", line 18, in load_state_dict
    state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by zoeouyang2543** [comment]
I had met this error when i operated:python ./Rerender_A_Video/webUI.py
when **block.launch(server_name='localhost')**
(base) oppoer@task-20240522083402-76752:/home/notebook/data/group/$ python ./Rerender_A_Video/webUI.py
logging improved.
Enabled sliced_attention.
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7860, 0, 0): cannot assign requested address
IMPORTANT: You are using gradio version 3.44.4, however version 4.29.0 is available, please upgrade.
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7861, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7862, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7863, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7864, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7865, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7866, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7867, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7868, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7869, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7870, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7871, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7872, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7873, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7874, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7875, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7876, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7877, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7878, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7879, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7880, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7881, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7882, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7883, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7884, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7885, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7886, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7887, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7888, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7889, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7890, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7891, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7892, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7893, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7894, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7895, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7896, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7897, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7898, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7899, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7900, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7901, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7902, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7903, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7904, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7905, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7906, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7907, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7908, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7909, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7910, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7911, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7912, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7913, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7914, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7915, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7916, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7917, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7918, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7919, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7920, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7921, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7922, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7923, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7924, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7925, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7926, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7927, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7928, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7929, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7930, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7931, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7932, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7933, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7934, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7935, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7936, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7937, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7938, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7939, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7940, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7941, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7942, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7943, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7944, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7945, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7946, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7947, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7948, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7949, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7950, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7951, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7952, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7953, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7954, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7955, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7956, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7957, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7958, 0, 0): cannot assign requested address
ERROR: [Errno 99] error while attempting to bind on address ('::1', 7959, 0, 0): cannot assign requested address
Traceback (most recent call last):
File "/home/notebook/data/group/oyp/./Rerender_A_Video/webUI.py", line 969, in
block.launch(server_name='localhost')
File "/home/oppoer/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1907, in launch
) = networking.start_server(
File "/home/oppoer/.local/lib/python3.10/site-packages/gradio/networking.py", line 207, in start_server
raise OSError(
OSError: Cannot find empty port in range: 7860-7959. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the server_port parameter to launch().

when **block.launch(share=True)**

logging improved.
Enabled sliced_attention.
Running on local URL:  http://127.0.0.1:7860
IMPORTANT: You are using gradio version 3.45.0, however version 4.29.0 is available, please upgrade.
--------

Could not create share link. Missing file: /home/oppoer/.local/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /home/oppoer/.local/lib/python3.10/site-packages/gradio


but URL:  http://127.0.0.1:7860 can not open.

when **block.launch(server_name='0.0.0.0')** 
but URL:  http://127.0.0.0:7860 can not open.

(base) @task-20240524201541-56387:/home/notebook/data/group$ hostname -i
10.237.43.30

**Comment by FurkanGozukara** [comment]
I have auto installers working

[**Turn Videos Into Animation With Just 1 Click - ReRender A Video Tutorial -  Installer For Windows**](https://youtu.be/a8oeCFyM5gA)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/ODpemx_36c1iPZc1kMwVv.png)](https://youtu.be/a8oeCFyM5gA)

 

[**Turn Videos Into Animation / 3D Just 1 Click - ReRender A Video Tutorial -  Installer For RunPod**](https://youtu.be/cVf9Qf_pKks)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/6MFsLs-f_GZR2L1Q6z413.png)](https://youtu.be/cVf9Qf_pKks)
