### ISSUE TITLE
 Issue with Model Loading in Rerender_A_Video Script

### ISSUE THREAD

**Issue by BryanHarrisScripts** [williamyang1991/Rerender_A_Video#21]
I hope this message finds you well. I wanted to bring to your attention an issue I've been experiencing while trying to run the Rerender_A_Video script as per the provided instructions. Below, I've detailed the problem and the steps I've taken so far.

When I attempt to run the Rerender_A_Video script using the provided configuration file `real2sculpture.json` without specifying a custom model file, I encounter an error related to model loading. The error message I receive is as follows:

````
No module 'xformers'. Proceeding without it.
ControlLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./deps/ControlNet/models/cldm_v15.yaml]
Loaded state_dict from [./models/control_sd15_canny.pth]
Traceback (most recent call last):
  File "C:\Users\bryan\Rerender_A_Video\rerender.py", line 462, in <module>
    rerender(cfg, args.one, args.key_video_path)
  File "C:\Users\bryan\Rerender_A_Video\rerender.py", line 89, in rerender
    model.load_state_dict(load_file(cfg.sd_model), strict=False)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\safetensors\torch.py", line 98, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: The system cannot find the file specified. (os error 2)
````

**Steps Taken So Far:**

1. I have followed the provided instructions for setting up the environment, including running the installation script to download the required models and dependencies.

2. I ensured that CUDA 11.8 is installed and checked for GPU availability using `torch.cuda.is_available()`.

3. I have made sure that the required libraries and packages are installed, as confirmed using `pip list`.

4. I have attempted to run the script both with and without specifying a custom model file. The issue persists in both cases.

5. I have verified the existence of the model file `control_sd15_canny.pth` in the specified directory.

Despite following the provided steps and confirming that the model file exists, the script encounters issues during model loading.

I kindly request your assistance in resolving this issue. If you require any additional information or logs to diagnose the problem, please let me know, and I will be happy to provide them.

**Comment by justinjohn0306** [comment]
> I hope this message finds you well. I wanted to bring to your attention an issue I've been experiencing while trying to run the Rerender_A_Video script as per the provided instructions. Below, I've detailed the problem and the steps I've taken so far.
> 
> When I attempt to run the Rerender_A_Video script using the provided configuration file `real2sculpture.json` without specifying a custom model file, I encounter an error related to model loading. The error message I receive is as follows:
> 
> ```
> No module 'xformers'. Proceeding without it.
> ControlLDM: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> making attention of type 'vanilla' with 512 in_channels
> Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
> making attention of type 'vanilla' with 512 in_channels
> Loaded model config from [./deps/ControlNet/models/cldm_v15.yaml]
> Loaded state_dict from [./models/control_sd15_canny.pth]
> Traceback (most recent call last):
>   File "C:\Users\bryan\Rerender_A_Video\rerender.py", line 462, in <module>
>     rerender(cfg, args.one, args.key_video_path)
>   File "C:\Users\bryan\Rerender_A_Video\rerender.py", line 89, in rerender
>     model.load_state_dict(load_file(cfg.sd_model), strict=False)
>                           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\bryan\AppData\Local\Programs\Python\Python311\Lib\site-packages\safetensors\torch.py", line 98, in load_file
>     with safe_open(filename, framework="pt", device=device) as f:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: The system cannot find the file specified. (os error 2)
> ```
> 
> **Steps Taken So Far:**
> 
> 1. I have followed the provided instructions for setting up the environment, including running the installation script to download the required models and dependencies.
> 2. I ensured that CUDA 11.8 is installed and checked for GPU availability using `torch.cuda.is_available()`.
> 3. I have made sure that the required libraries and packages are installed, as confirmed using `pip list`.
> 4. I have attempted to run the script both with and without specifying a custom model file. The issue persists in both cases.
> 5. I have verified the existence of the model file `control_sd15_canny.pth` in the specified directory.
> 
> Despite following the provided steps and confirming that the model file exists, the script encounters issues during model loading.
> 
> I kindly request your assistance in resolving this issue. If you require any additional information or logs to diagnose the problem, please let me know, and I will be happy to provide them.

make sure to download the sd checkpints from here and place them inside the "models" folder : https://civitai.com/models/7371/rev-animated?modelVersionId=19575
https://civitai.com/models/4201?modelVersionId=29460

you might wanna edit and add the name of the checkpoint inside the config file as well

**Comment by AbramovS1** [comment]
all models were loaded and there was still an error

Traceback (most recent call last):
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Rerender_A_Video\Rerender_A_Video\webUI.py", line 243, in process
    first_frame = process1(*args_wo_process3)
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "H:\Rerender_A_Video\Rerender_A_Video\webUI.py", line 258, in process1
    global_state.update_sd_model(cfg.sd_model, cfg.control_type)
  File "H:\Rerender_A_Video\Rerender_A_Video\webUI.py", line 97, in update_sd_model
    model.load_state_dict(load_file(sd_model_path), strict=False)
  File "C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\safetensors\torch.py", line 98, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
FileNotFoundError:

**Comment by gateway** [comment]
did you ever find a solution to this? Im stuck with the same thing, and even bails on this in the GUI..

**Comment by 343195246** [comment]
> did you ever find a solution to this? Im stuck with the same thing, and even bails on this in the GUI..
> 
> fixed.. silly me.. the config file was pointing to a model that I didnt have, i mean i had the model but was an updated one with small change in the name of the file

I had a similar problem, but I solved it by making sure the path to the stable model in the "sd_model_cfg.py" file was configured correctly.
