### ISSUE TITLE
Example error 

### ISSUE THREAD

**Issue by alyfreym** [williamyang1991/Rerender_A_Video#31]
Run - python3 rerender.py --cfg config/real2sculpture.json

`Traceback (most recent call last):
  File "/Users/alishershermatov/Documents/Projects/ML:AI/Rerender_A_Video/rerender.py", line 17, in <module>
    import src.import_util  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alishershermatov/Documents/Projects/ML:AI/Rerender_A_Video/src/import_util.py", line 10, in <module>
    import deps.ControlNet.share  # noqa: F401 E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alishershermatov/Documents/Projects/ML:AI/Rerender_A_Video/deps/ControlNet/share.py", line 2, in <module>
    from cldm.hack import disable_verbosity, enable_sliced_attention
  File "/Users/alishershermatov/Documents/Projects/ML:AI/Rerender_A_Video/deps/ControlNet/cldm/hack.py", line 4, in <module>
    import ldm.modules.encoders.modules
  File "/Users/alishershermatov/Documents/Projects/ML:AI/Rerender_A_Video/deps/ControlNet/ldm/modules/encoders/modules.py", line 7, in <module>
    import open_clip
  File "/opt/homebrew/lib/python3.11/site-packages/open_clip/__init__.py", line 2, in <module>
    from .factory import list_models, create_model, create_model_and_transforms, add_model_config
  File "/opt/homebrew/lib/python3.11/site-packages/open_clip/factory.py", line 13, in <module>
    from .model import CLIP, convert_weights_to_fp16, resize_pos_embed
  File "/opt/homebrew/lib/python3.11/site-packages/open_clip/model.py", line 17, in <module>
    from .timm_model import TimmModel
  File "/opt/homebrew/lib/python3.11/site-packages/open_clip/timm_model.py", line 10, in <module>
    import timm
  File "/opt/homebrew/lib/python3.11/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/opt/homebrew/lib/python3.11/site-packages/timm/models/__init__.py", line 28, in <module>
    from .maxxvit import *
  File "/opt/homebrew/lib/python3.11/site-packages/timm/models/maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1223, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1213, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory`

Python Version - 3.11.3
What version of Python is used in the project?
Machine - MacBook Pro (Apple M2 Max) Ventura 13.3.1

**Comment by alyfreym** [comment]
MacOS not tested.
