### ISSUE TITLE
Dataclasses error when running on Windows

### ISSUE THREAD

**Issue by Sashkan** [williamyang1991/Rerender_A_Video#36]
I'm trying to run the program on Windows 11, but it raises the following error:

```sh
Traceback (most recent call last):
  File "C:\Users\potra\Desktop\Work\AI\Rerender_A_Video\webUI.py", line 18, in <module>
    import src.import_util  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potra\Desktop\Work\AI\Rerender_A_Video\src\import_util.py", line 10, in <module>
    import deps.ControlNet.share  # noqa: F401 E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potra\Desktop\Work\AI\Rerender_A_Video\deps\ControlNet\share.py", line 2, in <module>
    from cldm.hack import disable_verbosity, enable_sliced_attention
  File "C:\Users\potra\Desktop\Work\AI\Rerender_A_Video\deps/ControlNet\cldm\hack.py", line 4, in <module>
    import ldm.modules.encoders.modules
  File "C:\Users\potra\Desktop\Work\AI\Rerender_A_Video\deps/ControlNet\ldm\modules\encoders\modules.py", line 7, in <module>
    import open_clip
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_clip\__init__.py", line 2, in <module>
    from .factory import list_models, create_model, create_model_and_transforms, add_model_config
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_clip\factory.py", line 13, in <module>
    from .model import CLIP, convert_weights_to_fp16, resize_pos_embed
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_clip\model.py", line 17, in <module>
    from .timm_model import TimmModel
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\site-packages\open_clip\timm_model.py", line 10, in <module>
    import timm
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\site-packages\timm\models\__init__.py", line 28, in <module>
    from .maxxvit import *
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\site-packages\timm\models\maxxvit.py", line 225, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\potra\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'timm.models.maxxvit.MaxxVitConvCfg'> for field conv_cfg is not allowed: use default_factory
```

I made sure to follow every step, including the installation requirements for Windows (Both installation steps ran smoothly)

Did I miss something ?

**Comment by williamyang1991** [comment]
Seems that it is a problem for python 3.11 (https://github.com/huggingface/pytorch-image-models/issues/1530#issuecomment-1302927759)
Maybe you can downgrade python to python 3.8.5 as we used.

**Comment by FurkanGozukara** [comment]
> Seems that it is a problem for python 3.11 ([huggingface/pytorch-image-models#1530 (comment)](https://github.com/huggingface/pytorch-image-models/issues/1530#issuecomment-1302927759)) Maybe you can downgrade python to python 3.8.5 as we used.

python 3.10.11 working good too

**Comment by SPOOKEXE** [comment]
If you want to stay on the later (unsupported) versions still, here is a fix for the issue:
https://github.com/huggingface/pytorch-image-models/issues/1530#issuecomment-1411722938

Also include 'field' in the "from dataclass import ..." statement at the top of the python file located at 'kohya_ss-22.1.0\venv\Lib\site-packages\timm\models\maxxvit.py'
