### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model'

### ISSUE THREAD

**Issue by oliverban** [williamyang1991/Rerender_A_Video#46]
Do gitpull for latest updates.
Start webUI.py
Click the topmost example in the Gradio interface
Click Run 1st Keyframe
Get this:

Traceback (most recent call last):
  File "c:\python\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "c:\python\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "c:\python\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "c:\python\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "c:\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\python\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "c:\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Oliver\Documents\Github\Rerender_A_Video\webUI.py", line 270, in process1
    model = ddim_v_sampler.model
AttributeError: 'NoneType' object has no attribute 'model'

**Comment by samxoo** [comment]
Seems like you are missing a model, find it in /models folder , get sure you see  revAnimated_v11 (if u use it) , get sure you see  control_sd15_hed.pth and control_sd15_canny.pth
