### ISSUE TITLE
TypeError: Can't convert object to 'str' for 'filename'

### ISSUE THREAD

**Issue by hugepump** [williamyang1991/Rerender_A_Video#57]
I was able to run it with Python 3.8.5, but the slow generation speed was due to the absence of the 'xformers' package. For some reasons, I upgraded Python to version 3.10. With the new version, I was able to generate the first frame successfully. However, I encountered an error when generating the keyframes.

Traceback (most recent call last):
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\test\miniconda3\envs\rerender5\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "G:\AI\Rerender_A_Video\webui.py", line 404, in process2
    frame = cv2.imread(cid)
TypeError: Can't convert object to 'str' for 'filename'

**Comment by williamyang1991** [comment]
We have revised the code and fixed this bug. 
Please update the code.
