### ISSUE TITLE
I have installed the library, but it still outputs "No module named 'torchtext.legacy'"

### ISSUE THREAD

**Issue by Damarcreative** [williamyang1991/Rerender_A_Video#86]
Traceback (most recent call last):
  File "/content/Rerender_A_Video/rerender.py", line 13, in <module>
    from pytorch_lightning import seed_everything
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/base.py", line 26, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/apply_func.py", line 30, in <module>
    from torchtext.legacy.data import Batch
ModuleNotFoundError: No module named 'torchtext.legacy'

**Comment by FurkanGozukara** [comment]
i have a 1 click installer for this

https://www.patreon.com/posts/89457537

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/19240467/fe7c40f1-3b57-450f-b2f5-23d7928e5c4c)

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/19240467/ac9827de-7cef-42ee-afce-8bdf099fc71b)

![image](https://github.com/williamyang1991/Rerender_A_Video/assets/19240467/e4c38e0b-b090-47ce-98b6-656e0abfc65a)
