### ISSUE TITLE
RuntimeError: The size of tensor a (1080) must match the size of tensor b (1280) at non-singleton dimension 2

### ISSUE THREAD

**Issue by 17freeman** [williamyang1991/Rerender_A_Video#90]
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\gxuya\Anaconda3\envs\liddle\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\gxuya\Anaconda3\envs\liddle\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\video_blend.py", line 110, in process_sequences
    process_one_sequence(i, video_sequence)
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\video_blend.py", line 97, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
                 ^^^^^^^^^^^^^^^
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\blender\guide.py", line 100, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\flow\flow_utils.py", line 237, in warp
    res = flow_warp(img, flow, mode=mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\flow\flow_utils.py", line 77, in flow_warp
    grid = coords_grid(b, h, w).to(flow.device) + flow  # [B, 2, H, W]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
RuntimeError: The size of tensor a (1080) must match the size of tensor b (1280) at non-singleton dimension 2
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\gxuya\Anaconda3\envs\liddle\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\gxuya\Anaconda3\envs\liddle\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\video_blend.py", line 110, in process_sequences
    process_one_sequence(i, video_sequence)
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\video_blend.py", line 97, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
                 ^^^^^^^^^^^^^^^
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\blender\guide.py", line 100, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\flow\flow_utils.py", line 237, in warp
    res = flow_warp(img, flow, mode=mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\flow\flow_utils.py", line 77, in flow_warp
    grid = coords_grid(b, h, w).to(flow.device) + flow  # [B, 2, H, W]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
RuntimeError: The size of tensor a (1080) must match the size of tensor b (1280) at non-singleton dimension 2
ebsynth: 3.9428999423980713
[ WARN:0@5.485] global loadsave.cpp:248 cv::findDecoder imread_('10_13_24\out_1\0002.jpg'): can't open/read file: check file path/integrity
[ WARN:0@5.486] global loadsave.cpp:248 cv::findDecoder imread_('10_13_24\out_1\0003.jpg'): can't open/read file: check file path/integrity
[ WARN:0@5.487] global loadsave.cpp:248 cv::findDecoder imread_('10_13_24\out_1\0004.jpg'): can't open/read file: check file path/integrity
[ WARN:0@5.489] global loadsave.cpp:248 cv::findDecoder imread_('10_13_24\out_5\0005.jpg'): can't open/read file: check file path/integrity
[ WARN:0@5.490] global loadsave.cpp:248 cv::findDecoder imread_('10_13_24\out_5\0002.jpg'): can't open/read file: check file path/integrity
[ WARN:0@5.491] global loadsave.cpp:248 cv::findDecoder imread_('10_13_24\out_5\0003.jpg'): can't open/read file: check file path/integrity
[ WARN:0@5.493] global loadsave.cpp:248 cv::findDecoder imread_('10_13_24\out_5\0004.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\video_blend.py", line 321, in <module>
    main(args)
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\video_blend.py", line 270, in main
    process_seq(video_sequence, i, blend_histogram, blend_gradient)
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\video_blend.py", line 199, in process_seq
    dist1s.append(load_error(bin_a, img_shape))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\video_blend.py", line 160, in load_error
    with open(bin_path, 'rb') as fp:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '10_13_24\\out_1\\0002.bin'


Hello, I got an error when running the video_blend program. The resolution of the image is 720*1280. The size of tensor a (1080) must match the size of tensor b (1280) at non-singleton dimension 2 appears for the first time.

**Comment by williamyang1991** [comment]
We cannot debug with this limited information.

can you print the shape of prev_img and self.flows[i - 1]?

```
File "C:\Users\gxuya\Documents\AIGC\sd-webui-aki\Rerender_A_Video-main\Rerender_A_Video-main\blender\guide.py", line 100, in get_cmd
warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
```

**Comment by 17freeman** [comment]
RuntimeError: The size of tensor a (1080) must match the size of tensor b (1280) at non-singleton dimension 2
prev_img ：(1080, 720, 3)
self.flows[i - 1]：torch.Size([1, 2, 1280, 720])

**Comment by williamyang1991** [comment]
It is quite strange why the size of your input frame is cropped to 1080?
Do you have any idea? Do you use the cropping function in the webUI?
In the  `0_13_24` folder, what is the size of your frame in `0_13_24/keys` and `0_13_24/video`?

**Comment by 17freeman** [comment]
Thank you for your reminder. It’s my problem. I forgot to reshape the image.
